#!/bin/bash
#
# Note runlevel 2345, 86 is the Start order and 85 is the Stop order
#
# chkconfig: 2345 86 85
# description: The loan-app app server. The server doesn't do much as most of the
# content is served from the root of the Apache web server.
#
# Below is the source function library, leave it be
. /etc/init.d/functions

# We need environment variables for passwords and the likes
. /home/ec2-user/.bash_profile


FOREVER=/usr/bin/forever
LOAN_APP_SERVER_SCRIPT=/home/loan/loan-app/server.js
SERVICE_NAME=loan-app

# options
LOGFILE=/var/log/loan-app.log
LOCKFILE=/var/lock/subsys/loan-app
MIN_UPTIME=5000
SPIN_SLEEP_TIME=2000


start(){
        $FOREVER \
           -a \
           --pidFile $LOCKFILE \
           -l $LOGFILE \
           --minUptime $MIN_UPTIME \
           --spinSleepTime $SPIN_SLEEP_TIME \
           start $LOAN_APP_SERVER_SCRIPT
}

stop(){
        $FOREVER stop $LOAN_APP_SERVER_SCRIPT
}

restart(){
         stop
         start
}

case "$1" in
        start)
                echo "Start service SERVICE_NAME"
                start
                ;;
        stop)
                echo "Stop service SERVICE_NAME"
                stop
                ;;
        restart)
                echo "Restart service SERVICE_NAME"
                restart
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
                ;;
esac
