#!/bin/bash
# Add this as a cron job: 
# 25 23 * * * /bin/bash -l /root/cron/backup

# (1) set up all the mysqldump variables
DATE=`date +"%Y%m%d"`
SQLFILE=$LOANS_BACKUP_DIR/db_loans_backup_$DATE.sql
DATABASE=$LOANS_DATABASE
USER=$LOANS_USER
PASSWORD=$LOANS_PASSWORD

# (2) in case you run this more than once a day,
# remove the previous version of the file
unalias rm     2> /dev/null
rm $SQLFILE     2> /dev/null

# (3) do the mysql database backup (dump)
mysqldump -u $USER -p$PASSWORD $DATABASE > $SQLFILE